"""
Report generation module for audit results.

Generates comprehensive security audit reports in multiple formats
including JSON, HTML, and Markdown.
"""

import json
from typing import Dict, List
from pathlib import Path
from datetime import datetime


class ReportGenerator:
    """Generates audit reports in various formats."""

    def generate(self, results: Dict, output_dir: str) -> str:
        """
        Generate audit report.

        Args:
            results: Audit results dictionary
            output_dir: Directory to save reports

        Returns:
            Path to the generated report
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # Generate timestamp for filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        contract_name = Path(results['contract']).stem

        # Generate JSON report
        json_path = output_path / f"{contract_name}_audit_{timestamp}.json"
        self._generate_json(results, json_path)

        # Generate Markdown report
        md_path = output_path / f"{contract_name}_audit_{timestamp}.md"
        self._generate_markdown(results, md_path)

        return str(md_path)

    def _generate_json(self, results: Dict, output_path: Path):
        """Generate JSON report."""
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)

    def _generate_markdown(self, results: Dict, output_path: Path):
        """Generate Markdown report."""
        contract_name = Path(results['contract']).stem
        summary = results.get('summary', {})

        md_content = f"""# Security Audit Report: {contract_name}

**Generated:** {results['timestamp']}
**Contract:** {results['contract']}

## Executive Summary

- **Total Vulnerabilities:** {summary.get('total_vulnerabilities', 0)}
- **Risk Score:** {summary.get('risk_score', 0):.1f}/100
- **Analyzers Run:** {', '.join(summary.get('analyzers_run', []))}

### Severity Breakdown

| Severity | Count |
|----------|-------|
| Critical | {summary.get('severity', {}).get('critical', 0)} |
| High | {summary.get('severity', {}).get('high', 0)} |
| Medium | {summary.get('severity', {}).get('medium', 0)} |
| Low | {summary.get('severity', {}).get('low', 0)} |
| Informational | {summary.get('severity', {}).get('informational', 0)} |

## Vulnerabilities

"""

        # Add each vulnerability
        for i, vuln in enumerate(results.get('vulnerabilities', []), 1):
            md_content += f"""### {i}. {vuln.get('type', 'Unknown').replace('_', ' ').title()}

**Severity:** {vuln.get('severity', 'unknown').upper()}
**Detector:** {vuln.get('detector', 'unknown')}

**Description:** {vuln.get('description', 'No description')}

"""
            if vuln.get('line'):
                md_content += f"**Line:** {vuln.get('line')}\n\n"

            if vuln.get('code_snippet'):
                md_content += f"""**Code:**
```solidity
{vuln.get('code_snippet')}
```

"""

        # Add analyzer details
        md_content += """## Analyzer Results

"""

        # Slither results
        slither = results.get('analyzers', {}).get('slither', {})
        if slither.get('success'):
            md_content += f"""### Slither Analysis

- **Status:** {'✓ Success' if slither.get('success') else '✗ Failed'}
- **Issues Found:** {len(slither.get('detectors', []))}

"""

        # Mythril results
        mythril = results.get('analyzers', {}).get('mythril', {})
        if mythril.get('success'):
            md_content += f"""### Mythril Analysis

- **Status:** {'✓ Success' if mythril.get('success') else '✗ Failed'}
- **Issues Found:** {len(mythril.get('issues', []))}

"""

        # AI analysis
        ai = results.get('analyzers', {}).get('ai', {})
        if ai.get('success'):
            md_content += f"""### AI Analysis

- **Risk Assessment:** {ai.get('risk_assessment', 'N/A')}
- **Recommendations:** {len(ai.get('recommendations', []))}

"""

            for rec in ai.get('recommendations', []):
                md_content += f"""#### {rec.get('title', 'Recommendation')}

**Severity:** {rec.get('severity', 'info').upper()}
{rec.get('description', '')}

**Recommendation:** {rec.get('recommendation', '')}

"""

        # Add footer
        md_content += """---

*This report was generated by AuditAgent - AI-Powered Smart Contract Security Auditor*
"""

        with open(output_path, 'w') as f:
            f.write(md_content)
